---
homebrew_tools:
    - asciinema
    - atuin
    - bat
    - dotnet
    - dust
    - duti
    - eza
    - fd
    - ffmpeg
    - fzf
    - gh
    - git-delta
    - git-lfs
    - jq
    - just
    - lazygit
    - lefthook
    - less
    - miller
    - nuget
    - osv-scanner
    - pandoc
    - pnpm
    - ripgrep
    - ripgrep-all
    - shellcheck
    - starship
    - tlrc
    - upx
    - yq
    - zoxide
    - zsh-autocomplete
    - zsh-autosuggestions
    - zsh-syntax-highlighting
