---
homebrew_tools:
    - asciinema
    - bat
    - bottom
    - eza
    - fd
    - ffmpeg
    - fzf
    - gh
    - git-delta
    - git-lfs
    - jq
    - just
    - lazygit
    - less
    - pandoc
    - pnpm
    - ripgrep
    - ripgrep-all
    - shellcheck
    - starship
    - upx
    - zoxide
    - zsh-autocomplete
    - zsh-autosuggestions
