---
apt_tools:
    - asciinema
    - bat
    - build-essential
    - containerd.io
    - dotnet-sdk-10.0
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-ce-rootless-extras
    - docker-compose-plugin
    - eza
    - fd-find
    - ffmpeg
    - flatpak
    - fzf
    - gh
    - git
    - git-delta
    - git-lfs
    - gnome-software-plugin-flatpak
    - gnupg
    - jq
    - just
    - less
    - lld
    - libpq-dev
    - p7zip-full
    - pandoc
    - pkg-config
    - poppler-utils
    - powershell
    - python3
    - python3-pip
    - ripgrep
    - shellcheck
    - upx-ucl
    - zoxide

snap_tools:
    - name: lazygit
      classic: false
