---
winget_tools:
    - ajeetdsouza.zoxide
    - ArtifexSoftware.GhostScript
    - BurntSushi.ripgrep.MSVC
    - Casey.Just
    - chmln.sd
    - Clement.bottom
    - Cppcheck.Cppcheck
    - dandavison.delta
    - errata-ai.Vale
    - evilmartians.lefthook
    - eza-community.eza
    - GitHub.cli
    - GitHub.GitLFS
    - Gitleaks.Gitleaks
    - Graphviz.Graphviz
    - Gyan.FFmpeg
    - ImageMagick.ImageMagick
    - JesseDuffield.lazygit
    - jftuga.less
    - johnkerl.miller
    - JohnMacFarlane.Pandoc
    - jqlang.jq
    - junegunn.fzf
    - koalaman.shellcheck
    - lycheeverse.lychee
    - Microsoft.NuGet
    - Microsoft.VisualStudio.2022.BuildTools
    - MikeFarah.yq
    - mvdan.shfmt
    - OliverBetz.ExifTool
    - Ollama.Ollama
    - pnpm.pnpm
    - PuTTY.PuTTY
    - rhysd.actionlint
    - sharkdp.bat
    - sharkdp.fd
    - sharkdp.hyperfine
    - Starship.Starship
    - UPX.UPX
    - XAMPPRocky.tokei
