---
winget_tools:
    - sharkdp.bat
    - Clement.bottom
    - dandavison.delta
    - eza-community.eza
    - junegunn.fzf
    - sharkdp.fd
    - GitHub.cli
    - GitHub.GitLFS
    - jqlang.jq
    - Casey.Just
    - JesseDuffield.lazygit
    - jftuga.less
    - Microsoft.NuGet
    - JohnMacFarlane.Pandoc
    - pnpm.pnpm
    - PuTTY.PuTTY
    - BurntSushi.ripgrep.MSVC
    - Starship.Starship
    - UPX.UPX
    - Microsoft.VisualStudio.2022.BuildTools
    - ajeetdsouza.zoxide
