---
- name: Install apt tools
  ansible.builtin.apt:
    name: "{{ apt_tools }}"
    state: present
  become: true

- name: Create fd symlink for fd-find
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: "{{ ansible_env.HOME }}/.local/bin/fd"
    state: link
  failed_when: false

- name: Enable Git LFS
  ansible.builtin.command: git lfs install
  changed_when: false

- name: Install snap tools
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop: "{{ snap_tools }}"
  become: true

- name: Check if Starship is installed
  ansible.builtin.command: which starship
  register: starship_check
  changed_when: false
  failed_when: false

- name: Install Starship
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes  # noqa: command-instead-of-module risky-shell-pipe
  changed_when: starship_check.rc != 0
  when: starship_check.rc != 0

- name: Check if container-structure-test is installed
  ansible.builtin.command: which container-structure-test
  register: cst_check
  changed_when: false
  failed_when: false

- name: Install container-structure-test
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
    dest: /usr/local/bin/container-structure-test
    mode: "0755"
  become: true
  when: cst_check.rc != 0

- name: Install ripgrep-all
  ansible.builtin.command: cargo install ripgrep_all
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rga"

- name: Check if pnpm is installed
  ansible.builtin.command: which pnpm
  register: pnpm_check
  changed_when: false
  failed_when: false

- name: Install pnpm  # noqa: command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: |
    wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
  changed_when: pnpm_check.rc != 0
  when: pnpm_check.rc != 0
