FROM ubuntu:latest
USER root

# https://stackoverflow.com/a/35976127
ARG DEBIAN_FRONTEND noninteractive

WORKDIR /build
COPY setup_ubuntu.sh .

# Although there is no need to run sudo in the Ubuntu container,
# it may be necessary for a user running this script.
RUN apt-get update && \
    apt-get -y install sudo && \
    sh setup_ubuntu.sh in_container

USER 1000
