---
- name: Install WinGet apps
  ansible.builtin.shell: >
    winget.exe install {{ item }}
    --accept-source-agreements
    --accept-package-agreements
    --silent
    --disable-interactivity
  loop: "{{ winget_apps }}"
  changed_when: false
  failed_when: false
