---
- name: Add user to docker group
  ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: true
  become: true

- name: Enable Docker service
  ansible.builtin.systemd:
      name: docker
      enabled: true
      state: started
  become: true
  failed_when: false # Gracefully skipped in containers

- name: Install VS Code extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  changed_when: false
  failed_when: false
