# Full reference: atuin default-config

history_filter = [
    "^export\\s.*API_KEY",
    "^export\\s.*API_TOKEN",
    "^export\\s.*PASSWORD",
    "^export\\s.*SECRET",
    "^export\\s.*TOKEN",
]

secrets_filter = true

update_check = false

search_mode = "fuzzy"

filter_mode_shell_up_key_binding = "session"

style = "compact"

show_preview = true
