# Defaults: https://clementtsang.github.io/bottom/nightly/configuration/config-file/default-config/

[flags]
dot_marker = true
unnormalized_cpu = true
battery = true
color = "gruvbox"
enable_gpu_memory = true
enable_cache_memory = true

[[row]]
ratio = 30
[[row.child]]
type = "cpu"
[[row]]
ratio = 40
[[row.child]]
ratio = 4
type = "mem"
[[row.child]]
ratio = 2
[[row.child.child]]
type = "disk"
[[row]]
ratio = 30
[[row.child]]
type = "net"
[[row.child]]
type = "proc"
default = true
