---
collections:
    - name: ansible.posix
      version: "2.2.0"
    - name: ansible.windows
      version: "3.6.1"
    - name: community.general
      version: "13.1.0"
    - name: community.windows
      version: "3.2.0"
