---
winget_apps:
    - 7zip.7zip
    - Anthropic.Claude
    - Mozilla.Firefox
    - SabaAmaury.Caesium
    - dbeaver.dbeaver
    - JGraph.Draw
    - Obsidian.Obsidian
    - Raindrop.Raindrop
    - Spotify.Spotify
    - Telegram.TelegramDesktop
    - Microsoft.VisualStudioCode
